import Foundation
#if canImport(FoundationXML)
import FoundationXML
#endif

/// Android string resources: `res/values/strings.xml` for the source locale and
/// `res/values-<locale>/strings.xml` for each translation.
public enum AndroidXMLFormat {
    public static func export(_ snapshot: Snapshot, options: ExportOptions = ExportOptions()) -> ExportResult {
        let context = ExportContext(snapshot: snapshot, options: options, platform: .android)
        var warnings: [String] = []
        var seenNames: [String: String] = [:]
        for key in context.keys {
            let name = KeyNaming.androidName(key.key)
            if let other = seenNames[name] {
                warnings.append("\"\(key.key)\" and \"\(other)\" both become \"\(name)\" on Android; \"\(key.key)\" was skipped")
            } else {
                seenNames[name] = key.key
            }
        }
        var files: [ExportedFile] = []
        for locale in snapshot.settings.locales {
            let isDefault = locale == context.source
            var body = ""
            for key in context.keys {
                let name = KeyNaming.androidName(key.key)
                guard seenNames[name] == key.key, let forms = context.forms(for: key, locale: locale) else { continue }
                let render = context.renderOptions(for: key)
                if isDefault, options.includeComments, !key.description.isEmpty {
                    body += "    <!-- \(escapeComment(key.description)) -->\n"
                }
                if key.isPlural {
                    body += "    <plurals name=\"\(name)\">\n"
                    for category in PluralCategory.allCases {
                        guard let text = forms[category] else { continue }
                        let value = escape(PlaceholderConverter.render(text, flavor: .android, options: render))
                        body += "        <item quantity=\"\(category.rawValue)\">\(value)</item>\n"
                    }
                    body += "    </plurals>\n"
                } else if let text = forms[.other] {
                    let value = escape(PlaceholderConverter.render(text, flavor: .android, options: render))
                    let translatable = key.doNotTranslate ? " translatable=\"false\"" : ""
                    body += "    <string name=\"\(name)\"\(translatable)>\(value)</string>\n"
                }
            }
            if body.isEmpty && !isDefault { continue }
            let folder = KeyNaming.androidValuesFolder(locale, isDefault: isDefault, legacyCodes: options.androidLegacyLanguageCodes)
            let xml = """
            <?xml version="1.0" encoding="utf-8"?>
            <!-- Generated by Runa. Edit strings in Runa; changes made here are overwritten. -->
            <resources>
            \(body)</resources>

            """
            files.append(ExportedFile(relativePath: "\(folder)/strings.xml", contents: Data(xml.utf8)))
        }
        return ExportResult(files: files, warnings: warnings)
    }

    static let allowedTags = try! NSRegularExpression(
        pattern: #"</?(b|i|u|s|strike|sup|sub|big|small|tt|br|font|annotation|a|span)(\s[^<>]*)?/?>"#, options: [.caseInsensitive])

    /// Escapes text for an Android string resource. Simple styling tags such as `<b>` are kept.
    public static func escape(_ text: String) -> String {
        let ns = text as NSString
        var output = ""
        var cursor = 0
        func escapePlain(_ plain: String) -> String {
            var result = ""
            for character in plain {
                switch character {
                case "\\": result += "\\\\"
                case "\"": result += "\\\""
                case "'": result += "\\'"
                case "\n": result += "\\n"
                case "\t": result += "\\t"
                case "&": result += "&amp;"
                case "<": result += "&lt;"
                case ">": result += "&gt;"
                default: result.append(character)
                }
            }
            return result
        }
        for match in allowedTags.matches(in: text, range: NSRange(location: 0, length: ns.length)) {
            output += escapePlain(ns.substring(with: NSRange(location: cursor, length: match.range.location - cursor)))
            output += ns.substring(with: match.range)
            cursor = match.range.location + match.range.length
        }
        output += escapePlain(ns.substring(from: cursor))
        if output.hasPrefix("@") || output.hasPrefix("?") { output = "\\" + output }
        // Android collapses whitespace, so protect leading, trailing and repeated spaces.
        var characters = Array(output)
        for index in characters.indices where characters[index] == " " {
            let leading = index == 0
            let trailing = index == characters.count - 1
            let repeated = index > 0 && (characters[index - 1] == " " || characters[index - 1] == "\u{1}")
            if leading || trailing || repeated { characters[index] = "\u{1}" }
        }
        return String(characters).replacingOccurrences(of: "\u{1}", with: "\\u0020")
    }

    static func escapeComment(_ text: String) -> String {
        text.replacingOccurrences(of: "--", with: "- -").replacingOccurrences(of: "\n", with: " ")
    }

    /// Reverses Android escaping: backslash escapes, quoted sections and whitespace collapsing.
    public static func unescape(_ raw: String) -> String {
        var output = ""
        var inQuotes = false
        var pendingSpace = false
        var characters = raw.makeIterator()
        var lookahead: [Character] = []
        func next() -> Character? { lookahead.isEmpty ? characters.next() : lookahead.removeFirst() }
        while let character = next() {
            if character == "\\" {
                guard let escaped = next() else { break }
                if pendingSpace { output.append(" "); pendingSpace = false }
                switch escaped {
                case "n": output.append("\n")
                case "t": output.append("\t")
                case "u":
                    var hex = ""
                    while hex.count < 4, let digit = next() {
                        if digit.isHexDigit { hex.append(digit) } else { lookahead.append(digit); break }
                    }
                    if let value = UInt32(hex, radix: 16), let scalar = Unicode.Scalar(value) { output.unicodeScalars.append(scalar) }
                default: output.append(escaped)
                }
            } else if character == "\"" {
                inQuotes.toggle()
            } else if !inQuotes, character.isWhitespace {
                pendingSpace = !output.isEmpty
            } else {
                if pendingSpace { output.append(" "); pendingSpace = false }
                output.append(character)
            }
        }
        return output
    }

    public static func parse(_ data: Data, locale: LocaleCode, file: String) throws -> (entries: [ImportedEntry], warnings: [String]) {
        let delegate = ResourceParser()
        let parser = XMLParser(data: data)
        parser.delegate = delegate
        guard parser.parse() else {
            throw FormatError.invalidFile(file, reason: parser.parserError?.localizedDescription ?? "Malformed XML")
        }
        var entries: [ImportedEntry] = []
        for resource in delegate.resources {
            let formatted = resource.formatted
            func clean(_ raw: String) -> String {
                let text = unescape(raw)
                return formatted ? text : text.replacingOccurrences(of: "%", with: "%%")
            }
            if resource.isPlural {
                var forms: [PluralCategory: String] = [:]
                for (category, raw) in resource.items { forms[category] = clean(raw) }
                entries.append(ImportedEntry(key: resource.name, locale: locale, isPlural: true, forms: forms, comment: resource.comment,
                                             translatable: resource.translatable, flavor: .android, file: file))
            } else {
                entries.append(ImportedEntry(key: resource.name, locale: locale, forms: [.other: clean(resource.text)], comment: resource.comment,
                                             translatable: resource.translatable, flavor: .android, file: file))
            }
        }
        return (entries, delegate.warnings)
    }

    private final class ResourceParser: NSObject, XMLParserDelegate {
        struct Resource {
            var name: String
            var isPlural: Bool
            var text = ""
            var items: [(PluralCategory, String)] = []
            var translatable = true
            var formatted = true
            var comment: String?
        }

        var resources: [Resource] = []
        var warnings: [String] = []
        private var current: Resource?
        private var currentItem: PluralCategory?
        private var itemText = ""
        private var depth = 0
        private var lastComment: String?

        func parser(_ parser: XMLParser, foundComment comment: String) {
            if current == nil { lastComment = comment.trimmingCharacters(in: .whitespacesAndNewlines) }
        }

        func parser(_ parser: XMLParser, didStartElement elementName: String, namespaceURI: String?, qualifiedName: String?,
                    attributes: [String: String] = [:])
        {
            if var resource = current {
                if resource.isPlural, elementName == "item", currentItem == nil {
                    currentItem = attributes["quantity"].flatMap(PluralCategory.init(rawValue:))
                    itemText = ""
                    if currentItem == nil { warnings.append("\(resource.name): unknown plural quantity \(attributes["quantity"] ?? "")") }
                    return
                }
                // Inline markup: keep styling tags as text, drop xliff:g wrappers.
                if !elementName.hasPrefix("xliff") {
                    let attributeText = attributes.sorted { $0.key < $1.key }.map { " \($0.key)=\"\($0.value)\"" }.joined()
                    appendText("<\(elementName)\(attributeText)>", to: &resource)
                    current = resource
                }
                depth += 1
                return
            }
            switch elementName {
            case "string", "plurals":
                guard let name = attributes["name"] else { return }
                current = Resource(name: name, isPlural: elementName == "plurals")
                current?.translatable = attributes["translatable"] != "false"
                current?.formatted = attributes["formatted"] != "false"
                current?.comment = lastComment
                lastComment = nil
            case "string-array":
                warnings.append("\(attributes["name"] ?? "string-array"): string arrays are not supported and were skipped")
            default: break
            }
        }

        private func appendText(_ text: String, to resource: inout Resource) {
            if currentItem != nil { itemText += text } else { resource.text += text }
        }

        func parser(_ parser: XMLParser, foundCharacters string: String) {
            guard var resource = current else { return }
            appendText(string, to: &resource)
            current = resource
        }

        func parser(_ parser: XMLParser, foundCDATA CDATABlock: Data) {
            guard var resource = current else { return }
            appendText(String(decoding: CDATABlock, as: UTF8.self), to: &resource)
            current = resource
        }

        func parser(_ parser: XMLParser, didEndElement elementName: String, namespaceURI: String?, qualifiedName: String?) {
            guard var resource = current else { return }
            if depth > 0 {
                depth -= 1
                if !elementName.hasPrefix("xliff") {
                    appendText("</\(elementName)>", to: &resource)
                    current = resource
                }
                return
            }
            if resource.isPlural, elementName == "item" {
                if let category = currentItem { resource.items.append((category, itemText)) }
                currentItem = nil
                current = resource
                return
            }
            if elementName == "string" || elementName == "plurals" {
                resources.append(resource)
                current = nil
            }
        }
    }
}
