import Foundation

/// Legacy Apple strings tables: `<locale>.lproj/Localizable.strings` for plain keys and
/// `Localizable.stringsdict` for plurals.
public enum AppleStringsFormat {
    public static func export(_ snapshot: Snapshot, options: ExportOptions = ExportOptions()) -> ExportResult {
        let context = ExportContext(snapshot: snapshot, options: options, platform: .ios)
        var files: [ExportedFile] = []
        var warnings: [String] = []
        for locale in snapshot.settings.locales {
            var strings = "/* Generated by Runa. Edit strings in Runa; changes made here are overwritten. */\n"
            var plurals: [String: Any] = [:]
            for key in context.keys {
                guard let forms = context.forms(for: key, locale: locale) else { continue }
                let render = context.renderOptions(for: key)
                if key.isPlural {
                    let order = render.argumentOrder
                    let variable = render.pluralVariable ?? "count"
                    let variableIndex = (order.firstIndex { $0.name == variable } ?? 0) + 1
                    let formatKey = order.count > 1 ? "%\(variableIndex)$#@\(variable)@" : "%#@\(variable)@"
                    var rule: [String: Any] = [
                        "NSStringFormatSpecTypeKey": "NSStringPluralRuleType",
                        "NSStringFormatValueTypeKey": "lld",
                    ]
                    for (category, text) in forms {
                        rule[category.rawValue] = PlaceholderConverter.render(text, flavor: .apple, options: render)
                    }
                    if render.pluralVariable == nil { warnings.append("\(key.key): plural without an {name:int} placeholder") }
                    plurals[key.key] = ["NSStringLocalizedFormatKey": formatKey, variable: rule]
                } else if let text = forms[.other] {
                    strings += "\n"
                    if options.includeComments, !key.description.isEmpty {
                        strings += "/* \(key.description.replacingOccurrences(of: "*/", with: "* /")) */\n"
                    }
                    strings += "\(quote(key.key)) = \(quote(PlaceholderConverter.render(text, flavor: .apple, options: render)));\n"
                }
            }
            let folder = "\(locale.rawValue).lproj"
            files.append(ExportedFile(relativePath: "\(folder)/\(options.tableName).strings", contents: Data(strings.utf8)))
            if !plurals.isEmpty,
                let data = try? PropertyListSerialization.data(fromPropertyList: plurals, format: .xml, options: 0)
            {
                files.append(ExportedFile(relativePath: "\(folder)/\(options.tableName).stringsdict", contents: data))
            }
        }
        return ExportResult(files: files, warnings: warnings)
    }

    static func quote(_ text: String) -> String {
        var output = "\""
        for character in text {
            switch character {
            case "\\": output += "\\\\"
            case "\"": output += "\\\""
            case "\n": output += "\\n"
            case "\t": output += "\\t"
            case "\r": output += "\\r"
            default: output.append(character)
            }
        }
        return output + "\""
    }

    /// Parses a `.strings` file (UTF-8 or UTF-16), keeping the comment above each entry.
    public static func parseStrings(_ data: Data, locale: LocaleCode, file: String) throws -> [ImportedEntry] {
        let text: String
        if data.starts(with: [0xFF, 0xFE]) || data.starts(with: [0xFE, 0xFF]) {
            text = String(data: data, encoding: .utf16) ?? ""
        } else {
            text = String(decoding: data, as: UTF8.self)
        }
        var scanner = StringsScanner(text: Array(text))
        var entries: [ImportedEntry] = []
        var comment: String?
        while true {
            scanner.skipWhitespace()
            guard let character = scanner.peek() else { break }
            if character == "/", scanner.peek(1) == "*" {
                comment = scanner.readBlockComment()
                continue
            }
            if character == "/", scanner.peek(1) == "/" {
                comment = scanner.readLineComment()
                continue
            }
            guard let key = scanner.readToken() else {
                throw FormatError.invalidFile(file, reason: "Expected a key near character \(scanner.index)")
            }
            scanner.skipWhitespaceAndComments()
            if scanner.peek() == ";" {
                scanner.index += 1
                entries.append(ImportedEntry(key: key, locale: locale, forms: [.other: key], comment: comment, flavor: .apple, file: file))
                comment = nil
                continue
            }
            guard scanner.peek() == "=" else { throw FormatError.invalidFile(file, reason: "Expected '=' after \"\(key)\"") }
            scanner.index += 1
            scanner.skipWhitespaceAndComments()
            guard let value = scanner.readToken() else { throw FormatError.invalidFile(file, reason: "Expected a value for \"\(key)\"") }
            scanner.skipWhitespaceAndComments()
            if scanner.peek() == ";" { scanner.index += 1 }
            entries.append(ImportedEntry(key: key, locale: locale, forms: [.other: value], comment: comment, flavor: .apple, file: file))
            comment = nil
        }
        return entries
    }

    /// Parses a `.stringsdict` file. Only single-variable plural rules are supported.
    public static func parseStringsdict(_ data: Data, locale: LocaleCode, file: String) throws -> (entries: [ImportedEntry], warnings: [String]) {
        guard let root = try PropertyListSerialization.propertyList(from: data, format: nil) as? [String: Any] else {
            throw FormatError.invalidFile(file, reason: "Not a dictionary")
        }
        var entries: [ImportedEntry] = []
        var warnings: [String] = []
        for (key, value) in root.sorted(by: { $0.key < $1.key }) {
            guard let dict = value as? [String: Any], let formatKey = dict["NSStringLocalizedFormatKey"] as? String else { continue }
            let variables = dict.filter { $0.key != "NSStringLocalizedFormatKey" }.compactMap { name, rule -> (String, [String: Any])? in
                guard let rule = rule as? [String: Any], rule["NSStringFormatSpecTypeKey"] as? String == "NSStringPluralRuleType" else { return nil }
                return (name, rule)
            }
            guard variables.count == 1, let (variable, rule) = variables.first else {
                warnings.append("\(key): \(variables.count) plural variables; only one is supported, skipped")
                continue
            }
            let wrapper = formatKey.replacingOccurrences(of: #"%(\d+\$)?#@\#(variable)@"#, with: "\u{0}", options: .regularExpression)
            var forms: [PluralCategory: String] = [:]
            for category in PluralCategory.allCases {
                guard let text = rule[category.rawValue] as? String else { continue }
                forms[category] = wrapper.replacingOccurrences(of: "\u{0}", with: text)
            }
            entries.append(ImportedEntry(key: key, locale: locale, isPlural: true, forms: forms, flavor: .apple, file: file))
        }
        return (entries, warnings)
    }
}

struct StringsScanner {
    let text: [Character]
    var index = 0

    func peek(_ offset: Int = 0) -> Character? {
        index + offset < text.count ? text[index + offset] : nil
    }

    mutating func skipWhitespace() {
        while let character = peek(), character.isWhitespace { index += 1 }
    }

    mutating func skipWhitespaceAndComments() {
        while true {
            skipWhitespace()
            if peek() == "/", peek(1) == "*" { _ = readBlockComment() } else if peek() == "/", peek(1) == "/" { _ = readLineComment() } else { return }
        }
    }

    mutating func readBlockComment() -> String {
        index += 2
        var comment = ""
        while let character = peek() {
            if character == "*", peek(1) == "/" {
                index += 2
                break
            }
            comment.append(character)
            index += 1
        }
        return comment.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    mutating func readLineComment() -> String {
        index += 2
        var comment = ""
        while let character = peek(), !character.isNewline {
            comment.append(character)
            index += 1
        }
        return comment.trimmingCharacters(in: .whitespaces)
    }

    mutating func readToken() -> String? {
        guard let first = peek() else { return nil }
        if first == "\"" {
            index += 1
            var value = ""
            while let character = peek() {
                index += 1
                if character == "\"" { return value }
                if character == "\\", let escaped = peek() {
                    index += 1
                    switch escaped {
                    case "n": value.append("\n")
                    case "t": value.append("\t")
                    case "r": value.append("\r")
                    case "U", "u":
                        var hex = ""
                        while hex.count < 4, let digit = peek(), digit.isHexDigit {
                            hex.append(digit)
                            index += 1
                        }
                        if let code = UInt32(hex, radix: 16), let scalar = Unicode.Scalar(code) { value.unicodeScalars.append(scalar) }
                    default: value.append(escaped)
                    }
                } else {
                    value.append(character)
                }
            }
            return nil
        }
        var value = ""
        while let character = peek(), character.isLetter || character.isNumber || "_.-$:/".contains(character) {
            value.append(character)
            index += 1
        }
        return value.isEmpty ? nil : value
    }
}
